In [326]:
import pandas as pd
import numpy as np

In [394]:
df = pd.read_csv("bank/bank-full.csv", sep=';')

In [395]:
df_new = df.loc[:, df.columns != 'loan']

In [396]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [397]:
df_new.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

## Question 1

In [398]:
df_new['education'].mode ()

0    secondary
Name: education, dtype: object

## Question 2

In [399]:
df_new_int = df_new[df_new.columns[df_new.dtypes == 'int64']]

In [400]:
corr_matrix = df_new_int.corr()
print(corr_matrix)

               age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

In [401]:
df_new

,age,job,marital,education,default,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,cellular,17,nov,361,2,188,11,other,no

In [402]:
df_new.y = (df_new.y == 'yes').astype(int)

<ipython-input-402-2a2fe49cb6a6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.y = (df_new.y == 'yes').astype(int)

In [403]:
df_new

,age,job,marital,education,default,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,unknown,5,may,261,1,-1,0,unknown,0
1,44,technician,single,secondary,no,29,yes,unknown,5,may,151,1,-1,0,unknown,0
2,33,entrepreneur,married,secondary,no,2,yes,unknown,5,may,76,1,-1,0,unknown,0
3,47,blue-collar,married,unknown,no,1506,yes,unknown,5,may,92,1,-1,0,unknown,0
4,33,unknown,single,unknown,no,1,no,unknown,5,may,198,1,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,cellular,17,nov,977,3,-1,0,unknown,1
45207,71,retired,divorced,primary,no,1729,no,cellular,17,nov,456,2,-1,0,unknown,1
45208,72,retired,married,secondary,no,5715,no,cellular,17,nov,1127,5,184,3,success,1
45209,57,blue-collar,married,secondary,no,668,no,telephone,17,nov,508,4,-1,0,unknown,0
45210,37,entrepreneur,married,secondary,no,2971,no,cellular,17,nov,361,2,188,11,other,0

In [404]:
from sklearn.model_selection import train_test_split

In [405]:
df_full_train, df_test = train_test_split(df_new, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [406]:
len(df_train), len(df_val), len(df_test)

(27126, 9042, 9043)

In [407]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [408]:
df_train

,age,job,marital,education,default,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,32,technician,single,tertiary,no,1100,yes,cellular,11,aug,67,1,-1,0,unknown,0
1,38,entrepreneur,married,secondary,no,0,yes,cellular,17,nov,258,1,-1,0,unknown,0
2,49,blue-collar,married,secondary,no,3309,yes,cellular,15,may,349,2,-1,0,unknown,0
3,37,housemaid,married,primary,no,2410,no,cellular,4,aug,315,1,-1,0,unknown,0
4,31,self-employed,married,tertiary,no,3220,no,cellular,26,aug,74,4,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27121,27,services,single,secondary,no,167,no,cellular,8,jul,606,2,-1,0,unknown,0
27122,40,technician,single,tertiary,no,693,no,cellular,30,jan,427,1,-1,0,unknown,0
27123,54,technician,divorced,secondary,no,0,yes,unknown,16,may,161,1,-1,0,unknown,0
27124,25,services,single,secondary,no,2311,no,cellular,21,jul,1105,2,-1,0,unknown,1
27125,30,management,single,tertiary,no,15,no,cellular,26,aug,252,2,-1,0,unknown,0

In [409]:
y_train = df_train.y.values
y_val = df_val.y.values
y_test = df_test.y.values

del df_train['y']
del df_val['y']
del df_test['y']

In [410]:
y_train

array([0, 0, 0, ..., 0, 1, 0])

In [411]:
categorical_columns = list(df_train.dtypes[df_train.dtypes == 'object'].index)
numeric_columns = list(df_train.dtypes[df_train.dtypes == 'int64'].index)

In [412]:
categorical_columns

['job',
 'marital',
 'education',
 'default',
 'housing',
 'contact',
 'month',
 'poutcome']

In [413]:
df_full_train.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [414]:
from sklearn.metrics import mutual_info_score

In [415]:
categorical_columns

['job',
 'marital',
 'education',
 'default',
 'housing',
 'contact',
 'month',
 'poutcome']

In [416]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.y)

## Question 3

In [417]:
mi = df_full_train[categorical_columns].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)

poutcome     0.029257
month        0.024774
contact      0.014164
housing      0.009800
job          0.007765
education    0.002458
marital      0.002019
default      0.000339
dtype: float64

In [418]:
from sklearn.feature_extraction import DictVectorizer

In [422]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_columns + numeric_columns].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numeric_columns].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [423]:
from sklearn.linear_model import LogisticRegression

In [424]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
# solver='lbfgs' is the default solver in newer version of sklearn
# for older versions, you need to specify it explicitly
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [426]:
test_dict = df_test[categorical_columns + numeric_columns].to_dict(orient='records')
X_test = dv.fit_transform(test_dict)
y_pred = model.predict(X_test)

In [427]:
y_pred = model.predict_proba(X_test)[:, 1]

In [428]:
y_pred

array([0.00816394, 0.03112457, 0.1767507 , ..., 0.01486787, 0.01109639,
       0.03532527])

In [429]:
final_y = (y_pred >= 0.5)

In [430]:
round((final_y == y_test).mean(), 2)

0.9

# Question 6

In [431]:
model = LogisticRegression(C=0.01, penalty='l2', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
round((final_y == y_val).mean(), 3)

c:\Program Files\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.89

In [432]:
model = LogisticRegression(C=0.1, penalty='l2', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
round((final_y == y_val).mean(), 3)

c:\Program Files\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.889

In [433]:
model = LogisticRegression(C=1, penalty='l2', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
round((final_y == y_val).mean(), 3)

c:\Program Files\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.892

In [434]:
model = LogisticRegression(C=10, penalty='l2', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
round((final_y == y_val).mean(), 3)

c:\Program Files\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.892

In [435]:
model = LogisticRegression(C=100, penalty='l2', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
round((final_y == y_val).mean(), 3)

c:\Program Files\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.893

# Question 5

In [436]:
df_new = df.loc[:, df.columns != 'loan']
df_new.loc[:, 'y'] = (df_new.loc[:, 'y'] == 'yes').astype(int)

df_new

<ipython-input-436-336e7a6033bb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.loc[:, 'y'] = (df_new.loc[:, 'y'] == 'yes').astype(int)
<ipython-input-436-336e7a6033bb>:2: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_new.loc[:, 'y'] = (df_new.loc[:, 'y'] == 'yes').astype(int)

,age,job,marital,education,default,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,unknown,5,may,261,1,-1,0,unknown,0
1,44,technician,single,secondary,no,29,yes,unknown,5,may,151,1,-1,0,unknown,0
2,33,entrepreneur,married,secondary,no,2,yes,unknown,5,may,76,1,-1,0,unknown,0
3,47,blue-collar,married,unknown,no,1506,yes,unknown,5,may,92,1,-1,0,unknown,0
4,33,unknown,single,unknown,no,1,no,unknown,5,may,198,1,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,cellular,17,nov,977,3,-1,0,unknown,1
45207,71,retired,divorced,primary,no,1729,no,cellular,17,nov,456,2,-1,0,unknown,1
45208,72,retired,married,secondary,no,5715,no,cellular,17,nov,1127,5,184,3,success,1
45209,57,blue-collar,married,secondary,no,668,no,telephone,17,nov,508,4,-1,0,unknown,0
45210,37,entrepreneur,married,secondary,no,2971,no,cellular,17,nov,361,2,188,11,other,0

In [443]:
df_new = df.loc[:, df.columns != 'loan']
df_new.y = (df_new.y == 'yes').astype(int)

##df_new = df_new.drop('balance', axis=1)


df_full_train, df_test = train_test_split(df_new, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)


df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.y.values
y_val = df_val.y.values
y_test = df_test.y.values

del df_train['y']
del df_val['y']
del df_test['y']


categorical_columns = list(df_train.dtypes[df_train.dtypes == 'object'].index)
numeric_columns = list(df_train.dtypes[df_train.dtypes == 'int64'].index)

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_columns + numeric_columns].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numeric_columns].to_dict(orient='records')
X_val = dv.transform(val_dict)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
accuracy_ori = (final_y == y_val).mean()
accuracy_ori

<ipython-input-443-017fe3934afa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.y = (df_new.y == 'yes').astype(int)

0.9007962840079629

In [444]:
df_new = df.loc[:, df.columns != 'loan']
df_new.y = (df_new.y == 'yes').astype(int)

df_new = df_new.drop('age', axis=1)


df_full_train, df_test = train_test_split(df_new, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)


df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.y.values
y_val = df_val.y.values
y_test = df_test.y.values

del df_train['y']
del df_val['y']
del df_test['y']


categorical_columns = list(df_train.dtypes[df_train.dtypes == 'object'].index)
numeric_columns = list(df_train.dtypes[df_train.dtypes == 'int64'].index)

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_columns + numeric_columns].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numeric_columns].to_dict(orient='records')
X_val = dv.transform(val_dict)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
accuracy_age = (final_y == y_val).mean()
accuracy_age

<ipython-input-444-72647bec3228>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.y = (df_new.y == 'yes').astype(int)

0.900353904003539

In [445]:
df_new = df.loc[:, df.columns != 'loan']
df_new.y = (df_new.y == 'yes').astype(int)

df_new = df_new.drop('balance', axis=1)


df_full_train, df_test = train_test_split(df_new, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)


df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.y.values
y_val = df_val.y.values
y_test = df_test.y.values

del df_train['y']
del df_val['y']
del df_test['y']


categorical_columns = list(df_train.dtypes[df_train.dtypes == 'object'].index)
numeric_columns = list(df_train.dtypes[df_train.dtypes == 'int64'].index)

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_columns + numeric_columns].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numeric_columns].to_dict(orient='records')
X_val = dv.transform(val_dict)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
accuracy_bal = (final_y == y_val).mean()
accuracy_bal

<ipython-input-445-8c03a8f51acd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.y = (df_new.y == 'yes').astype(int)

0.9009068790090687

In [446]:
df_new = df.loc[:, df.columns != 'loan']
df_new.y = (df_new.y == 'yes').astype(int)

df_new = df_new.drop('marital', axis=1)


df_full_train, df_test = train_test_split(df_new, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)


df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.y.values
y_val = df_val.y.values
y_test = df_test.y.values

del df_train['y']
del df_val['y']
del df_test['y']


categorical_columns = list(df_train.dtypes[df_train.dtypes == 'object'].index)
numeric_columns = list(df_train.dtypes[df_train.dtypes == 'int64'].index)

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_columns + numeric_columns].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numeric_columns].to_dict(orient='records')
X_val = dv.transform(val_dict)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
accuracy_mari = (final_y == y_val).mean()
accuracy_mari

<ipython-input-446-dc78d32c4f28>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.y = (df_new.y == 'yes').astype(int)

0.9009068790090687

In [447]:
df_new = df.loc[:, df.columns != 'loan']
df_new.y = (df_new.y == 'yes').astype(int)

df_new = df_new.drop('previous', axis=1)


df_full_train, df_test = train_test_split(df_new, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)


df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.y.values
y_val = df_val.y.values
y_test = df_test.y.values

del df_train['y']
del df_val['y']
del df_test['y']


categorical_columns = list(df_train.dtypes[df_train.dtypes == 'object'].index)
numeric_columns = list(df_train.dtypes[df_train.dtypes == 'int64'].index)

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_columns + numeric_columns].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numeric_columns].to_dict(orient='records')
X_val = dv.transform(val_dict)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
y_pred = model.predict_proba(X_val)[:, 1]
final_y = (y_pred >= 0.5)
accuracy_pre = (final_y == y_val).mean()
accuracy_pre

<ipython-input-447-329f28ecb2d0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.y = (df_new.y == 'yes').astype(int)

0.9009068790090687